package server

import (
	"testing"

	"github.com/labyrinthdns/labyrinth/dns"
	"github.com/labyrinthdns/labyrinth/resolver"
)

// TestBuildResponse_SingleOPT pins RFC 6891 §6.1.1: "a DNS message MUST NOT
// contain more than one OPT resource record." The OPT is a per-hop
// pseudo-record generated by the responder — it is never relayed. A fresh
// recursive resolution copies the upstream authoritative server's additional
// section verbatim into result.Additional, which carries that server's own
// OPT. buildResponse then appends the resolver's own OPT for the client. If
// the inbound OPT is not stripped first, the response ships TWO OPT records:
// dig reports "malformed message packet" and strict stubs reject it.
//
// This bug surfaced only on COLD positive answers (the cache path stores no
// OPT, so cached replies were always clean) which is exactly the every-query
// path for a working recursive resolver, so it is a high-impact regression to
// guard.
func TestBuildResponse_SingleOPT(t *testing.T) {
	h := testHandler()

	query := &dns.Message{
		Header: dns.Header{
			ID:    0xabcd,
			Flags: dns.NewFlagBuilder().SetRD(true).Build(),
		},
		Questions: []dns.Question{{Name: "opt.test", Type: dns.TypeA, Class: dns.ClassIN}},
		EDNS0:     &dns.EDNS0{UDPSize: 4096, DOFlag: true},
	}

	// Simulate the upstream response passthrough: the authoritative server's
	// own OPT rides along in result.Additional next to real glue.
	upstreamOPT := dns.BuildOPT(4096, true)
	result := &resolver.ResolveResult{
		RCODE: dns.RCodeNoError,
		Answers: []dns.ResourceRecord{
			{
				Name: "opt.test", Type: dns.TypeA, Class: dns.ClassIN,
				TTL: 60, RDLength: 4, RData: []byte{192, 0, 2, 1},
			},
		},
		Additional: []dns.ResourceRecord{
			{
				Name: "ns.opt.test", Type: dns.TypeA, Class: dns.ClassIN,
				TTL: 60, RDLength: 4, RData: []byte{192, 0, 2, 53},
			},
			upstreamOPT,
		},
	}

	resp, err := h.buildResponse(query, result)
	if err != nil {
		t.Fatalf("buildResponse: %v", err)
	}
	parsed, err := dns.Unpack(resp)
	if err != nil {
		t.Fatalf("unpack (response must be well-formed): %v", err)
	}

	optCount := 0
	for _, rr := range parsed.Additional {
		if rr.Type == dns.TypeOPT {
			optCount++
		}
	}
	if optCount != 1 {
		t.Fatalf("response has %d OPT records, want exactly 1 (RFC 6891 §6.1.1)", optCount)
	}
}

// TestBuildResponse_NonEDNSClientGetsNoOPT pins the companion invariant: a
// client that did NOT send EDNS must never receive an OPT, even when the
// upstream response carried one that flowed into result.Additional. Relaying
// the upstream OPT to a plain-DNS stub would push EDNS onto a client that
// never negotiated it.
func TestBuildResponse_NonEDNSClientGetsNoOPT(t *testing.T) {
	h := testHandler()

	query := &dns.Message{
		Header: dns.Header{
			ID:    0xbeef,
			Flags: dns.NewFlagBuilder().SetRD(true).Build(),
		},
		Questions: []dns.Question{{Name: "noedns.test", Type: dns.TypeA, Class: dns.ClassIN}},
		// No EDNS0 on the query.
	}

	result := &resolver.ResolveResult{
		RCODE: dns.RCodeNoError,
		Answers: []dns.ResourceRecord{
			{
				Name: "noedns.test", Type: dns.TypeA, Class: dns.ClassIN,
				TTL: 60, RDLength: 4, RData: []byte{192, 0, 2, 2},
			},
		},
		Additional: []dns.ResourceRecord{dns.BuildOPT(4096, false)},
	}

	resp, err := h.buildResponse(query, result)
	if err != nil {
		t.Fatalf("buildResponse: %v", err)
	}
	parsed, err := dns.Unpack(resp)
	if err != nil {
		t.Fatalf("unpack: %v", err)
	}
	for _, rr := range parsed.Additional {
		if rr.Type == dns.TypeOPT {
			t.Fatalf("non-EDNS client received a leaked OPT record (RFC 6891 §6.1.1)")
		}
	}
}
