package web

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
)

// SetupRequest represents the JSON body for the setup completion endpoint.
type SetupRequest struct {
	ListenAddr     string `json:"listen_addr"`
	WebAddr        string `json:"web_addr"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	MaxCacheSize   int    `json:"max_cache_size"`
	MaxDepth       int    `json:"max_depth"`
	RateLimitRate  float64 `json:"rate_limit_rate"`
	RateLimitBurst int    `json:"rate_limit_burst"`
	LogLevel       string `json:"log_level"`
	LogFormat      string `json:"log_format"`
}

// handleSetupStatus handles GET /api/setup/status — returns setup state.
func (s *AdminServer) handleSetupStatus(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		jsonResponse(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	jsonResponse(w, http.StatusOK, map[string]interface{}{
		"setup_required": !s.setupDone,
		"version":        Version,
	})
}

// handleSetupComplete handles POST /api/setup/complete — creates initial config.
func (s *AdminServer) handleSetupComplete(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonResponse(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}

	if s.setupDone {
		jsonResponse(w, http.StatusConflict, map[string]string{"error": "setup already completed"})
		return
	}

	var req SetupRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonResponse(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}

	// Hash the password
	var passwordHash string
	if req.Password != "" {
		var err error
		passwordHash, err = HashPassword(req.Password)
		if err != nil {
			jsonResponse(w, http.StatusInternalServerError, map[string]string{"error": "failed to hash password"})
			return
		}
	}

	// Apply defaults
	if req.ListenAddr == "" {
		req.ListenAddr = ":53"
	}
	if req.WebAddr == "" {
		req.WebAddr = "127.0.0.1:8080"
	}
	if req.MaxCacheSize <= 0 {
		req.MaxCacheSize = 100000
	}
	if req.MaxDepth <= 0 {
		req.MaxDepth = 30
	}
	if req.LogLevel == "" {
		req.LogLevel = "info"
	}
	if req.LogFormat == "" {
		req.LogFormat = "json"
	}

	// Write config file
	cfgPath := "labyrinth.yaml"
	if err := writeConfigYAML(cfgPath, req, passwordHash); err != nil {
		jsonResponse(w, http.StatusInternalServerError, map[string]string{"error": "failed to write config: " + err.Error()})
		return
	}

	s.setupDone = true
	s.logger.Info("setup completed, config written", "path", cfgPath)

	jsonResponse(w, http.StatusOK, map[string]string{"status": "setup complete"})
}

// writeConfigYAML writes a labyrinth.yaml config file using fmt.Fprintf (no YAML library).
func writeConfigYAML(path string, cfg SetupRequest, passwordHash string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create config file: %w", err)
	}
	defer f.Close()

	// Escape YAML string values that might contain special characters
	escYAML := func(s string) string {
		if strings.ContainsAny(s, ":#{}[]&*!|>'\"%@`") || s == "" {
			return fmt.Sprintf("%q", s)
		}
		return s
	}

	fmt.Fprintf(f, "# Labyrinth DNS configuration\n")
	fmt.Fprintf(f, "# Generated by setup wizard\n\n")

	fmt.Fprintf(f, "server:\n")
	fmt.Fprintf(f, "  listen_addr: %s\n", escYAML(cfg.ListenAddr))
	fmt.Fprintf(f, "\n")

	fmt.Fprintf(f, "resolver:\n")
	fmt.Fprintf(f, "  max_depth: %d\n", cfg.MaxDepth)
	fmt.Fprintf(f, "  qname_minimization: true\n")
	fmt.Fprintf(f, "  prefer_ipv4: true\n")
	fmt.Fprintf(f, "\n")

	fmt.Fprintf(f, "cache:\n")
	fmt.Fprintf(f, "  max_entries: %d\n", cfg.MaxCacheSize)
	fmt.Fprintf(f, "\n")

	if cfg.RateLimitRate > 0 {
		fmt.Fprintf(f, "security:\n")
		fmt.Fprintf(f, "  rate_limit:\n")
		fmt.Fprintf(f, "    enabled: true\n")
		fmt.Fprintf(f, "    rate: %g\n", cfg.RateLimitRate)
		if cfg.RateLimitBurst > 0 {
			fmt.Fprintf(f, "    burst: %d\n", cfg.RateLimitBurst)
		}
		fmt.Fprintf(f, "\n")
	}

	fmt.Fprintf(f, "logging:\n")
	fmt.Fprintf(f, "  level: %s\n", escYAML(cfg.LogLevel))
	fmt.Fprintf(f, "  format: %s\n", escYAML(cfg.LogFormat))
	fmt.Fprintf(f, "\n")

	fmt.Fprintf(f, "web:\n")
	fmt.Fprintf(f, "  enabled: true\n")
	fmt.Fprintf(f, "  addr: %s\n", escYAML(cfg.WebAddr))
	if cfg.Username != "" {
		fmt.Fprintf(f, "  auth:\n")
		fmt.Fprintf(f, "    username: %s\n", escYAML(cfg.Username))
		fmt.Fprintf(f, "    password_hash: %s\n", escYAML(passwordHash))
	}

	return nil
}
